# Starship prompt
#
# ~/.config/starship.toml is generated by themes/starship-build from the bar and
# palette currently selected — switch with `theme-set <name>` / `bar-set <name>`.
# Starship re-reads that file on every prompt, so a switch needs no reload.

eval "$(starship init zsh)"

# ── transient prompt ───────────────────────────────────────────────────────
# Collapse the strip to a bare ❯ once a command is submitted, so scrollback is
# one line per command instead of a wall of capsules — what
# POWERLEVEL9K_TRANSIENT_PROMPT did.
#
# Starship has no transience for zsh. The feature exists for fish, bash (ble.sh),
# PowerShell and cmd only — see starship.rs/advanced-config — so it is done here
# with zle.
#
# The character module is asked for the colour rather than hardcoding one, so
# this follows theme-set like everything else. STARSHIP_CMD_STATUS is set by
# starship's own precmd and holds the status the visible prompt was drawn with,
# so a failed command keeps its red ❯ as it scrolls away.
# starship sets PROMPT ONCE, as a promptsubst template:
#
#   PROMPT='$(starship prompt --status="${STARSHIP_CMD_STATUS:-}" ...)'
#
# which zsh re-evaluates every prompt. It is never re-assigned, so overwriting it
# here would replace the strip permanently -- full prompt once, bare ❯ forever
# after. The template is kept and put back by a precmd hook below.
_starship_prompt_template=$PROMPT
_starship_rprompt_template=$RPROMPT

_starship_transient_prompt() {
  PROMPT="$(starship module character --status=${STARSHIP_CMD_STATUS:-0})"
  RPROMPT=''
  zle .reset-prompt
}

_starship_restore_prompt() {
  PROMPT=$_starship_prompt_template
  RPROMPT=$_starship_rprompt_template
}
precmd_functions+=(_starship_restore_prompt)

# add-zle-hook-widget, not `zle -N zle-line-finish`: zsh-autosuggestions already
# owns that widget (it shows as user:azhw:zle-line-finish — azhw being this same
# hook system). Registering through it appends; assigning the widget directly
# would silently drop autosuggestions' handler.
if autoload -Uz add-zle-hook-widget 2>/dev/null; then
  zle -N _starship_transient_prompt
  add-zle-hook-widget line-finish _starship_transient_prompt
fi

