## name: Gruvbox Dark (medium)
## author: Pavel Pertsev (morhetz)
## license: MIT
## upstream: https://github.com/morhetz/gruvbox
## blurb: Retro groove colour scheme, warm and low contrast

background              #282828
foreground              #ebdbb2
cursor                  #928374
cursor_text_color       #282828

selection_background    #ebdbb2
selection_foreground    #928374

url_color               #83a598

active_border_color     #fabd2f
inactive_border_color   #504945
bell_border_color       #fb4934

active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836
tab_bar_background      #1d2021

mark1_foreground #282828
mark1_background #fabd2f
mark2_foreground #282828
mark2_background #8ec07c
mark3_foreground #282828
mark3_background #d3869b

color0  #665c54
color8  #7c6f64
color1  #cc241d
color9  #fb4934
color2  #98971a
color10 #b8bb26
color3  #d79921
color11 #fabd2f
color4  #458588
color12 #83a598
color5  #b16286
color13 #d3869b
color6  #689d6a
color14 #8ec07c
color7  #a89984
color15 #bdae93
